apiVersion: operator.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: custom-istio
  namespace: istio-system
spec:
  profile: empty  
  components:
    base:
      enabled: true  
    pilot:
      enabled: true  
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        namespace: istio-system
        k8s:
          service:
            type: LoadBalancer
            loadBalancerIP: 
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  values:
    global:
      platform: gke
      proxy:
        logLevel: info
      meshID: mesh-default
    meshConfig:
      trustDomain: cluster.local
      enableProtocolSniffingInbound: true
      enableProtocolSniffingOutbound: true
    cni:
      cniBinDir: ""